# Generated by Django 5.1.4 on 2025-01-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohio', '0002_remove_hotel_hotel_price_remove_hotel_hotel_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
